### ISSUE TITLE
型`StaticImageData`をパッケージ`next/image`から読み込むようにする

### ISSUE THREAD

**Issue by ReoHakase** [astronomy-club-at-nitic/quiz-rally#62]
<img width="1243" alt="image" src="https://github.com/astronomy-club-at-nitic/quiz-rally/assets/16751535/fe748843-fc68-4e47-a3ac-ee9e501a7d25">

普通に`export`されてるかも！！

**Comment by dino3616** [comment]
あ一応補足すると、これ `@/constant/question` とかで直接 `next/image` import せずに一旦 `@types/` を挟みたいっていう経緯があった感じす
なのでリファクタするとしたら `@types/static-image-data` で `export type from 'next/image'` する感じすかね

**Comment by ReoHakase** [comment]
挟む必要性があんまりよくわかんないけどやっときます

**Comment by dino3616** [comment]
画像をオブジェクトとして扱うときは少なくとも `src`, `height`, `width` を持っていてほしいっていう型情報を隠蔽するためっすね
`@/constant` は依存木の葉ではない && `next` がいるような根でもないので

までもその `@/constant` で `next/image` の `StaticImageData` として import しちゃってるので、もっとちゃんとするなら注入する必要とかある気はします

**Comment by ReoHakase** [comment]
一行でもいいからコード内にコメントが欲しかったかな
> @/constant で next/image の StaticImageData として import しちゃってる

これがあって最初見た時冗長なコードに見えたから
